import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Toaster } from "@/components/ui/sonner";
import SessionProviderWrapper from "@/provider/session-provider";
import "./globals.css";
import { AlertDialogProvider } from "@/provider/alert-dialog-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "SolutifCX",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<SessionProviderWrapper>
			<AlertDialogProvider>
				<html lang="en">
					<body className={inter.className}>{children}</body>
					<Toaster position="top-right" richColors />
				</html>
			</AlertDialogProvider>
		</SessionProviderWrapper>
	);
}
